name: Node.js CI/CD

on:
  push:
    branches: [ main, dev ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      id: tests
      run: npm test

    - name: Set package name for dev branch
      if: github.ref == 'refs/heads/dev'
      run: |
        npm config set package:name $(npm pkg get name | tr -d '"' | sed 's/$/-dev/')
    

    - name: Publish to Public NPM
      if: github.ref == 'refs/heads/main'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPMPUBLISH}}

    - name: Publish to Private NPM
      if: github.ref == 'refs/heads/dev'
      run: npm publish --access private
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPMPUBLISH}}
